-   id: postgres
    name: postgres
    description: "Check psql formatting"
    entry: postgres
    types: [sql]
    language: script
-   id: message
    name: commit-message
    description: "Validate commit message"
    entry: message.py
    stages: [commit-msg]
    language: script
